name: Renovate
on:
  workflow_dispatch:
    inputs:
      log-level:
        description: "Log level"
        required: true
        default: "INFO"
        type: choice
        options:
          - "TRACE"
          - "DEBUG"
          - "INFO"
          - "WARN"
          - "ERROR"
  schedule:
    - cron: "0/15 * * * *"

concurrency:
  # Only let one renovate job run at a time
  group: renovate

jobs:
  renovate:
    runs-on: ubuntu-latest
    env:
      LOG_LEVEL: ${{ github.event.inputs.log-level || 'INFO' }}
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@0c94129d48b4e92addf23686b8a735b3057a0448 # v40.2.5
        with:
          configurationFile: global-config.json
          token: ${{ secrets.RENOVATE_TOKEN }}
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL)$"
