name: Renovate
on:
  workflow_dispatch:
    inputs:
      log-level:
        description: "Log level"
        required: true
        default: "INFO"
        type: choice
        options:
          - "TRACE"
          - "DEBUG"
          - "INFO"
          - "WARN"
          - "ERROR"
  schedule:
    - cron: "0/15 * * * *"

concurrency:
  # Only let one renovate job run at a time
  group: renovate

jobs:
  renovate:
    runs-on: ubuntu-latest
    env:
      LOG_LEVEL: ${{ github.event.inputs.log-level || 'INFO' }}
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@13f127373fd3dc43b41b0979e37ba570d6c2b8f4 # v43.0.0
        with:
          configurationFile: global-config.json
          token: ${{ secrets.RENOVATE_TOKEN }}
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL)$"
