name: Renovate
on:
  workflow_dispatch:
    inputs:
      log-level:
        description: "Log level"
        required: true
        default: "INFO"
        type: choice
        options:
          - "TRACE"
          - "DEBUG"
          - "INFO"
          - "WARN"
          - "ERROR"
  schedule:
    - cron: "0/15 * * * *"

concurrency:
  # Only let one renovate job run at a time
  group: renovate

jobs:
  renovate:
    runs-on: ubuntu-latest
    env:
      LOG_LEVEL: ${{ github.event.inputs.log-level || 'INFO' }}
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@89c8a9b60f5bc8395658abab8f40f96e4b490ebf # v39.1.0
        with:
          configurationFile: global-config.json
          token: ${{ secrets.RENOVATE_TOKEN }}
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL)$"
